name = "protozoa_dev"
version = "1.0.0"

description = "CLI tool for the Protozoa Protocol Buffers library"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "protozoa_dev" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
protozoa = ">= 2.0.3 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
shellout = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glance = ">= 5.0.0 and < 6.0.0"
birdie = ">= 1.4.1 and < 2.0.0"
